name: Build CreativeRequests Plugin

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-home-cache-cleanup: true
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Clean Gradle cache
      run: |
        rm -rf ~/.gradle/caches/*/executionHistory/
        rm -rf ~/.gradle/caches/*/fileHashes/
        rm -rf ~/.gradle/caches/*/fileContent/
    
    - name: Build with Gradle
      run: ./gradlew --no-daemon --stacktrace clean shadowJar
      
    - name: Fallback build with Maven (if Gradle fails)
      if: failure()
      run: mvn clean package
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CreativeRequests-Plugin
        path: |
          build/libs/CreativeRequests-*.jar
          target/CreativeRequests-*.jar
        if-no-files-found: error

    - name: Check commit message
      id: check_commit
      run: |
        commit_msg=$(git log -1 --pretty=%B)
        if [[ $commit_msg == release:* ]]; then
          echo "is_release=true" >> $GITHUB_OUTPUT
          version=$(echo $commit_msg | sed 's/release: //')
        else
          echo "is_release=false" >> $GITHUB_OUTPUT
          version="beta-$(git rev-parse --short HEAD)"
        fi
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Create Release
      if: steps.check_commit.outputs.is_release == 'true'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/libs/CreativeRequests-*.jar
          target/CreativeRequests-*.jar
        tag_name: v${{ steps.check_commit.outputs.version }}
        name: Release ${{ steps.check_commit.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Create Beta Release
      if: steps.check_commit.outputs.is_release != 'true'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/libs/CreativeRequests-*.jar
          target/CreativeRequests-*.jar
        tag_name: beta-${{ github.sha }}
        name: Beta Build ${{ steps.check_commit.outputs.version }}
        draft: false
        prerelease: true
        generate_release_notes: true
